apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-platform-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-platform-app
  template:
    metadata:
      labels:
        app: cloud-platform-app
    spec:
      containers:
        - name: cloud-platform-app
          image: cloud-platform-app:1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 20