replicaCount: 3

image:
  repository: ghcr.io/shravsz/cloud-infrastructure-platform
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5000
  targetPort: 5000

containerPort: 5000

health:
  path: /health
  readinessInitialDelay: 5
  readinessPeriod: 10
  livenessInitialDelay: 10
  livenessPeriod: 20